### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by Ethyling**
Add aarch64 support

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Ethyling** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
This errors...
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

Note that 1.7.1 was recently released, and I'll need to revamp the build system a bit. I think it's still worth iterating on what you have in the PR here already, and then it should be quite straightforward to adapt for the new version.

Also, thanks for the PR! :)

**Comment by Ethyling** [comment]
> This errors...
> 
> ```
> CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> -- Configuring incomplete, errors occurred!
> ```
> 
> Note that 1.7.1 was recently released, and I'll need to revamp the build system a bit. I think it's still worth iterating on what you have in the PR here already, and then it should be quite straightforward to adapt for the new version.
> 
> Also, thanks for the PR! :)

I think this should be fixed by adding `make` as build dependency on Linux

**Comment by h-vetinari** [comment]
> I think this should be fixed by adding `make` as build dependency on Linux

Certainly not for all of linux, it works fine without on x86...

But do whatever you think is necessary; let me know when the aarch-CI turns green and I'll have a look.

**Comment by Ethyling** [comment]
> > I think this should be fixed by adding `make` as build dependency on Linux
> 
> Certainly not for all of linux, it works fine without on x86...
> 
> But do whatever you think is necessary; let me know when the aarch-CI turns green and I'll have a look.

I think it's because the `conda-forge/linux-anvil` image provide `make` on `x86_64` and not on `aarch64`:
```
$ docker run --rm quay.io/condaforge/linux-anvil which make
/usr/bin/make
```
```
docker run --rm quay.io/condaforge/linux-anvil-aarch64 which make
/usr/bin/which: no make in (/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin)
```

**Comment by h-vetinari** [comment]
@Ethyling 
Yeah, that would have been my guess. Might want to fix this (or raise an issue) in https://github.com/conda-forge/docker-images.

OTOH, perhaps it's cleaner to just depend on the environment-make rather than the image-one...

**Comment by h-vetinari** [comment]
Seems the test suite is hanging somewhere on aarch. I'm switching on artefact persistence so that someone with an aarch machine can dig into this. Probably needs upstream fixes.

**Comment by Ethyling** [comment]
Close in favor of https://github.com/conda-forge/faiss-split-feedstock/pull/51

**Pull request closed without merging**
