### PR TITLE
Update CUDA arches for CUDA 11.8 / sm_90 support.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bdice** [comment]
@jakirkham Does this look like an appropriate change to the feedstock for local builds using newer CUDA versions? It also improves ARM / CUDA compatibility for CUDA 11.1+.

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
> This will likely require similar changes as were made in PR ( [conda-forge/ptxcompiler-feedstock#7](https://github.com/conda-forge/ptxcompiler-feedstock/pull/7) ) to build with a newer CUDA version (if that is what is desired)

Shouldn't this come from c-f infra rather than having to manually set this in cbc.yaml?

**Comment by jakirkham** [comment]
Since this PR was started, CUDA 11.8 was added to conda-forge with a migrator ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4834 )

Here is the bot PR ( https://github.com/conda-forge/faiss-split-feedstock/pull/70 )

As the logic in the recipe has changed a fair bit, found it easier to add the CUDA 11.8 change in the bot PR. Though please let me know if anything else is needed. Commented on the relevant portion of the diff to highlight this change for discussion: https://github.com/conda-forge/faiss-split-feedstock/pull/70#discussion_r1407092111

Also please let me know if there's anything else needed from this PR

**Comment by bdice** [comment]
Closing as stale.

**Pull request closed without merging**
