### PR TITLE
Change Faiss to compile on Windows

### PR DESCRIPTION
**Pull request by mdouze**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@h-vetinari This is for a try

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@mdouze @beauby Let me know if there's something I can do to help wake this PR from its slumber ;-)

**Comment by beauby** [comment]
@h-vetinari Hi, thanks for your work! We're currently in the process of porting Faiss to Windows, and will get back to you soon.

**Pull request closed without merging**
