### PR TITLE
Rerun for GPU builds

### PR DESCRIPTION
**Pull request by h-vetinari**
Two GPU builds failed on master after merging #1 due to the workers running out of space. Let's try this again.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by h-vetinari** [comment]
@isuruf 
Has something changed with the cuda-images or some limit on azure?

What was working in #1 is now failing consistently for the 10.1 & 10.2 builds due to running out of space on the device.

**Comment by h-vetinari** [comment]
@conda-forge/core

Is there anyway to deal with `No space left on device` on azure? Can we configure bigger disks for the workers? These builds ran through (effectively) unchanged in #1 and have been failing now.

**Comment by xhochy** [comment]
Have a look at https://github.com/conda-forge/omniscidb-feedstock/issues/5

**Comment by h-vetinari** [comment]
Thanks a lot for the tip @xhochy :)

**Pull request merged**
