### PR TITLE
Build with AVX2 support

### PR DESCRIPTION
**Pull request by h-vetinari**
From the discussion in #23, it became clear that the archspec-stuff isn't ready for primetime yet, and that it's better to follow the upstream model of compiling both for a generic target _as well as_  for avx2, and distinguish by availability at load time.

Since the patch for avx2-detection would have been non-trivial, I upstreamed this first in https://github.com/facebookresearch/faiss/pull/1600.

Not sure that I've translated everything correctly from the upstream [`build-lib.sh`](https://github.com/facebookresearch/faiss/blob/master/conda/faiss/build-lib.sh) / [`build-pkg.sh`](https://github.com/facebookresearch/faiss/blob/master/conda/faiss/build-pkg.sh), or even if `-DFAISS_OPT_LEVEL=avx2` is respected (or working) on windows.

PS. The extension stuff in `setup.py` was a learning from #22, but is required here as well. Once everything is ironed out, I'll happily upstream this as well.

~PPS. Currently based on #26, will rebase once that goes in.~

### CODE REVIEW

**Comment by h-vetinari** [comment]
@beauby @mdouze

FYI, this is pretty much how I'm thinking of supporting the AVX2 stuff; also testing both with and without AVX2 support (as you can see from the sequence of commands, resp. the logs).

The patch for `EXT_SUFFIX` is actually something that's been necessary for PyPy anyway (see #22) - not sure what your appetite is for supporting that, but I'd be happy to upstream a version of this as well.

I'm planning to merge this latest on Monday, in case you have opinions about any of it. 🙃

**Comment by h-vetinari** [comment]
@beauby @mdouze @wickedfoo
Not sure what `-DFAISS_OPT_LEVEL=avx2` does behind the scenes (i.e. does it also support windows, for example?), but could it perhaps be necessary to pass other explicit compiler flags?

I ask because I would have (naïvely) expected the AVX2-enabled test suite to run through faster, but the times are very comparable between with & without AVX2 support.

So either the tests (or the problem sizes) don't really allow the AVX2 acceleration to make a significant impact, or something is not working yet with the integration (either in this PR, or generally).

**Comment by h-vetinari** [comment]
Ping @beauby @mdouze
Would love to hear your thoughts on this one. :)

**Comment by beauby** [comment]
@h-vetinari Apologies for the late reply. So the `FAISS_OPT_LEVEL=avx2` triggers this: https://github.com/facebookresearch/faiss/blob/master/faiss/CMakeLists.txt#L153, which basically sets some compile options (`-mavx2 -mfma -mf16c -mpopcnt`) enabling some optimized instruction sets, and changes the target output to `libfaiss_avx2`. No other flags should be needed. We haven't tested those options with VC++.

Regarding test times, I'm not sure a large difference can be observed (@mdouze  can you confirm?) due to the limited problem size. In order to make sure the resulting library was indeed compiled with AVX instructions, you can check `objdump -d libfaiss*.a | awk '/[ \t]vxorps[ \t]/' (it should output something when `FAISS_OPT_LEVEL` is set to `avx2` and nothing otherwise). Next thing to be extra cautious is to make sure the loader loads the right library.

Regarding the EXT_SUFFIX patch, it looks good, feel free to open a PR on our repo and I'll review it.

**Comment by h-vetinari** [comment]
Cool, thanks for the feedback! :)

> Next thing to be extra cautious is to make sure the loader loads the right library.

That's exactly the reason I'm switching to `INFO` level for the logger so that I can see which library was loaded, and testing it twice with & without AVX2. 🙃 

That got me thinking - this check can even be automated. Have a look at the test set-up, maybe it's interesting for you as well (fingers crossed that it works on first try, but you get the idea).

**Comment by h-vetinari** [comment]
Good lesson for always automating things - I had overlooked that things weren't working under windows (and with py36).

**Comment by h-vetinari** [comment]
@beauby, seems that CMake Switch isn't windows compatible (just looking at the logs in more detail, because the avx2-lib couldn't be loaded on windows):

```
cl : Command line warning D9002: ignoring unknown option '-mavx2' [D:\bld\faiss-split_1613049237715\work\_build_avx2\faiss\faiss.vcxproj]
cl : Command line warning D9002: ignoring unknown option '-mfma' [D:\bld\faiss-split_1613049237715\work\_build_avx2\faiss\faiss.vcxproj]
cl : Command line warning D9002: ignoring unknown option '-mf16c' [D:\bld\faiss-split_1613049237715\work\_build_avx2\faiss\faiss.vcxproj]
cl : Command line warning D9002: ignoring unknown option '-mpopcnt' [D:\bld\faiss-split_1613049237715\work\_build_avx2\faiss\faiss.vcxproj]
```

**Comment by h-vetinari** [comment]
This turned out to be a bigger exercise than expected, but aside from upstreaming the patches, it should be pretty much ready. Considering how the intrinsics stuff is somewhat of a first for me, I'd appreciate some extra eyeballs @conda-forge/core (not so much for the patches, but the recipe).

Some background on the building approach is in the OP, but it's actually the testing side of things that I'm happiest with - both the version with as well as the version without AVX2 is run through the whole upstream test suite, including an automated check that the right library is loaded on import (only downside being that I haven't managed to package it into a single `run_test.py` due to the way NPY_DISABLE_CPU_FEATURES interacts with loading numpy).

From that point of view, everything seems to be working fine, but I still get warnings of the sort:
```
WARNING (faiss,lib/python3.6/site-packages/faiss/_swigfaiss_avx2.cpython-36m-x86_64-linux-gnu.so): $RPATH/libfaiss_avx2.so not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```

I'll wait for a bit of feedback here and for the upstreaming PRs, but will hopefully merge sometime next week (assuming nothing else comes up).

**Comment by h-vetinari** [comment]
@beauby @mdouze @wickedfoo
I have another question: how important is an AVX2-enabled GPU-build in your opinion? In other words, how much code is there that cannot be offloaded to the GPU and would benefit from AVX2? Because I'm considering if double the CI time (2h->4h) is worth that gain, especially if it might not end up being very relevant after all.

**Comment by h-vetinari** [comment]
@conda-forge/core, for some reason, the package hashing is broken for here `libfaiss` (which I've split into two outputs for with & without AVX2, using a jinja2-loop to keep DRY) - note the `h1234567`:

```
validation results:
{
  [...]
  "linux-64/libfaiss-avx2-1.7.0-hb573701_1_cpu.tar.bz2": true,
  "linux-64/libfaiss-1.7.0-h1234567_1_cpu.tar.bz2": true,
  [...]
}
{
  [...]
  "osx-64/libfaiss-avx2-1.7.0-h694c701_1_cpu.tar.bz2": true,
  "osx-64/libfaiss-1.7.0-h1234567_1_cpu.tar.bz2": true,
  [...]
}
```

On the windows side, the problem seems to become a bit clearer - apparently, the host dependencies aren't being picked up?! (should be the same between `libfaiss` and `libfaiss-avx2`)
```
INFO :: The inputs making up the hashes for the built packages are as follows:
{
  [...]
  "libfaiss-1.7.0-h1234567_1_cpu": {
    "recipe": {
      "channel_targets": "conda-forge main",
      "target_platform": "win-64"
    }
  },
  "libfaiss-avx2-1.7.0-hf21947d_1_cpu": {
    "recipe": {
      "channel_targets": "conda-forge main",
      "cuda_compiler_version": "None",
      "cxx_compiler": "vs2019",
      "libblas": "3.8 *netlib",
      "liblapack": "3.8 *netlib",
      "target_platform": "win-64"
    }
  }
}
```

**Comment by beckermr** [comment]
I am guessing this is the jinja2 loop. I have a vague memory that jinja2 control flow can confuse conda-build when computing hashes.

**Comment by beckermr** [comment]
See this issue: https://github.com/conda/conda-build/issues/4090

**Comment by beckermr** [comment]
Selectors are ugly but will probably get you on your way.

**Comment by h-vetinari** [comment]
Thanks for that reference @beckermr. Unfortunately, my situation here is more complicated than the one in that issue, and I'm not going to duplicate 50+ lines of recipe and try to keep them in sync. I've switched the order in the loop so that `libfaiss` gets a correct hash, while I don't care enough about `libfaiss-avx2` to butcher the recipe here.

**Pull request merged**
